// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
import { ensureDatabaseUrl } from "./src/lib/database-url";

/**
 * Build DATABASE_URL from individual components if provided.
 * This supports AWS RDS-managed secrets where username and password
 * are injected separately for automatic password rotation support.
 *
 * Expected environment variables when using RDS-managed secret:
 * - DB_HOST: RDS endpoint (e.g., mydb.xxxxx.us-east-1.rds.amazonaws.com)
 * - DB_PORT: Database port (default: 5432)
 * - DB_NAME: Database name
 * - DB_USERNAME: Username from RDS-managed secret
 * - DB_PASSWORD: Password from RDS-managed secret
 * - DB_SSL: Whether to use SSL (default: true for RDS)
 */
// Construct DATABASE_URL from RDS components (or use explicit value) for Prisma CLI and runtime usage.
const databaseUrl = ensureDatabaseUrl();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl || env("DATABASE_URL"),
  },
});
